### ISSUE TITLE
Some problem with the regex

### ISSUE THREAD

**Issue by Sai-Teja** [JPeer264/node-rename-css-selectors#10]
So, I tried to run this on materialize.css and materialize.js which were part of my project. The problem was, It also changed

     ".2": "tny",
	".4": "tng",
	".36": "ze",
	".42": "trl",
	".53": "qq",
	".58": "trc",

in js and css files which lead to a lot of errors please fix this asap.

**Comment by Sai-Teja** [comment]
I fixed this by changing

selectors in regex.java to

    selectors: /(#|\.)[^0-9\s:.{)[>+,\s][^\s:.{)[>+,\s]+/g, // matches all selectors beginning with . or # - e.g. .matching#alsomatch .matchmetoo


I have one more problem, there is css class new in one of the libraries Is there a way to ignore that?

**Comment by JPeer264** [comment]
Thanks for this issue. I don't know if I understand you correct. Is your issue that you do not want to change specific classes in your css file? The new regex seems to ignore those numbers.

I am currently in the middle of refactoring `rename-css-selectors`. So in the current version you have to install `npm i -S rcs-core` manually (this will change in v2). And type following **before** you process all your files:

```js
const rcsCore = require('rcs-core');
const rcs = require('rename-css-selectors');

// I think it might be a good feature to exclude a specific regex
// but that I will implement this feature soon
rcsCore.selectorLibrary.setExclude([
  'new',
  '2',
]);

// your processing
rcs.process();
```

**Comment by JPeer264** [comment]
Please open again if you think this is still an issue
