### ISSUE TITLE
Not completely renamed if className starts with name of another class

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rename-css-selectors#12]
HI @JPeer264!

Found issue with selectors renaming:

```css
.Grid_area:hover .Grid_sortIcons,.Grid_sortIcons.Grid_sortIconsSorted{...}
.Grid_clickable .Grid_trBody:hover .Grid_areaHighlight{...}
```
renamed to 
```css
.n_:hover .nz,.nz.nzSorted{...}
.rt .rn:hover .n_Highlight{...}
```

We have two classes (`Grid_areaHighlight` and `Grid_sortIconsSorted`), that start with names of existing classes (`Grid_area`, `Grid_sortIcons`). And seems like renaming mistakenly replace part of second class with already renamed one

**Comment by JPeer264** [comment]
Hey, thanks for your issue.

Ah I see, this shouldn't happen. I will take a look at it tonight asap.

**Comment by JPeer264** [comment]
I was too curious and fixed that already in v`1.3.3`.
Feel free to reopen this issue if this bug still exists.

**Comment by klimashkin** [comment]
Cool, thanks!
Seems like it's not publish in npm yet

**Comment by klimashkin** [comment]
Problem fixed!
But I found regression with colors, filed #14
