### ISSUE TITLE
"exclude" in .rcsrc doesn't work

### ISSUE THREAD

**Issue by Stephen-X** [JPeer264/node-rename-css-selectors#18]
It's part of a series of issues I found, so I'm going to reuse the base test case and open separate issues for each of them 😄 I'm developing on Windows btw; not sure if these are all platform specific bugs.

## Issue Description:

Selectors put inside "exclude" of `.rcsrc` in project root doesn't get excluded.

## Steps to reproduce this issue:

1. Create a simple project with the following code:

`index.html`:

```html
<html>
    <head>
        <meta name="description" content="Fire in the hole!">
        <link rel="stylesheet" href="style.css">
    </head>
    <body div class="in wf-active">
        <p>Fire in the hole!</p>
        <script src="script.js"></script>
    </body>
</html>
```

`style.css`:

```css
.wf-active {
    color: red;
}

.in {
    font-weight: bold;
}
```

`script.js`:

```javascript
console.log('Fire in the hole!');
```

`.rcsrc`:

```
{
    "exclude": [
        "wf-active"
    ]
}
```

`selector_obfs.js`:

```javascript
const rcs = require('rename-css-selectors')

rcs.loadMapping('./temp/renaming_map.json')

rcs.processCss('style.css', {newPath: 'temp'}, err => {
    rcs.process(['script.js', 'index.html'], {newPath: 'temp'}, err => {
        rcs.generateMapping('./temp', { overwrite: true }, err => {
            // the mapping file is now saved
        })
    })
})
```

2. Run RCS by `node selector_obfs.js`. The selector "wf-active" still got renamed everywhere:

E.g. in `styles.css`:
```css
.t {
    color: red;
}

.n {
    font-weight: bold;
}
```

**Comment by JPeer264** [comment]
Oh, that shouldn't happen. I will fix this

**Comment by JPeer264** [comment]
@Stephen-X btw. I am just looking over some issues. Have you tried to add `rcs.includeConfig()` in your code?

**Comment by grkblood13** [comment]
Any idea when this might get fixed?

**Comment by JPeer264** [comment]
Is this still an issue with `.includeConfig()`?

**Comment by grkblood13** [comment]
It works with includeConfig, but the documentation isnt really clear on how to use it. It's be helpful if there was an example in the main README.md to make it obvious since exclusion is really important with this tool

**Comment by JPeer264** [comment]
@grkblood13 I updated the README. If it is still not clear how to use it, please comment here again.

Closed in favor of https://github.com/JPeer264/node-rename-css-selectors/commit/abaf6d4aba3e7b4f0dfb06269175d753dbbec7d9
