### ISSUE TITLE
RCS stops renaming selectors between two ' symbols

### ISSUE THREAD

**Issue by Stephen-X** [JPeer264/node-rename-css-selectors#21]
It's part of a series of issues I found, so I'm going to reuse the base test case and open separate issues for each of them 😄 I'm developing on Windows btw; not sure if these are all platform specific bugs.

## Issue Description:

As the title said. This is probably due to inappropriate escaping.

## Steps to reproduce this issue:

1. Create a simple project with the following code:

`index.html` (notice the single quote `'` in `<title>` and `<p>`):

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>'</title>
    <link rel="stylesheet" href="style.css" type="text/css">
</head>

<body class="in wf-active">
    <p>'</p>
    <script src="script.js"></script>
</body>

</html>
```

`style.css`:

```css
.wf-active {
    color: red;
}

.in {
    font-weight: bold;
}
```

`script.js`:

```javascript
console.log('Fire in the hole!');
```

`selector_obfs.js`:

```javascript
const rcs = require('rename-css-selectors')

rcs.loadMapping('./temp/renaming_map.json')

rcs.processCss('style.css', {newPath: 'temp'}, err => {
    rcs.process(['script.js', 'index.html'], {newPath: 'temp'}, err => {
        rcs.generateMapping('./temp', { overwrite: true }, err => {
            // the mapping file is now saved
        })
    })
})
```

2. Run RCS by `node selector_obfs.js`. Notice that `.in` and `.wf-active` is not renamed in the new `index.html`.

**Comment by JPeer264** [comment]
Furthermore, in HTML just attributes of `class` and `id` are renamed. If you want to trigger more attributes you can add them with [these options](https://github.com/JPeer264/node-rcs-core/blob/master/docs/api/replace.md#html), as documented in [processHtml](https://github.com/JPeer264/node-rename-css-selectors/blob/master/docs/api/processHtml.md)
