### ISSUE TITLE
Proper handling of selectors containing escaped characters

### ISSUE THREAD

**Issue by mfarhadpur** [JPeer264/node-rename-css-selectors#35]
Thanks for your work on this. I noticed it currently does not handle selectors that contain escaped characters such as `:` used by [TailwindCSS](https://github.com/tailwindcss/tailwindcss), e.g. `.focus\:bg-white`.

**Comment by JPeer264** [comment]
Hey @mfarhadpur, I never saw this style of CSS. You think it is ok if `.focus\:bg-white` gets renamed to e.g. `.a`? Or must it be `.a\:bg-white`?

**Comment by mfarhadpur** [comment]
Thanks for the reply. Yes, that should be fine. Just the [backslash](https://www.w3.org/International/questions/qa-escapes#css_identifiers) is only used in the CSS, e.g. the above class is used as `focus:bg-white` in HTML and JS.

**Comment by JPeer264** [comment]
Alright. I'll implement it the next days.

**Comment by mfarhadpur** [comment]
Thanks!

**Comment by JPeer264** [comment]
@mfarhadpur please checkout `rename-css-selectors@3.1.2`. If your issue is not yet resolved, feel free to reopen this issue.

**Comment by mfarhadpur** [comment]
@JPeer264 Thanks for working on this. I think you should re-open the issue, as there are still bugs.

So, basically such a selector is defined as:

```css
.focus\:bg-white:focus {
  background-color: #fff;
}
```

And used as:

```html
<a href="#" class="focus:bg-white">Link<a>
```

Note that unescaped  `:`  denotes a pseudo-class in CSS and should not be removed. Right now, the class remains untouched in HTML/JS .i.e. `focus:bg-white` instead of being renamed to say `b`, and in CSS it is changed to:

```css
.b {
  background-color: #fff;
}
```

While it should be:

```css
.b:focus {
  background-color: #fff;
}
```

**Comment by JPeer264** [comment]
Uff. Sorry I totally missed that. I hope I can fix this soon.

**Comment by mfarhadpur** [comment]
No worries, whenever you find the time. Just to reiterate, there's also the issue of renames not being applied in HTML/JS.

**Comment by JPeer264** [comment]
Seems like I did not write enough tests for it ;) Gonna be fixed the next iteration.

**Comment by mfarhadpur** [comment]
@JPeer264 Thanks! Everything seems to be working fine. Would you mind also updating the PostCSS plugin to use the latest core, whenever you have the time?

**Comment by JPeer264** [comment]
Done. `postcss-rcs@2.0.0`
