### ISSUE TITLE
Rename CSS Custom Properties (Variables)

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rename-css-selectors#37]
Hi! 
We are dropping IE11 support in our company, so finally we start leveraging CSS Variables natively 🎉 But as classnames they might become pretty wordy, so it would be nice to have an option to mangle them too along with classnames and animation names!

**Comment by JPeer264** [comment]
Hey happy to hear that you are dropping IE11 :) My company is still using it for a while unfortunately. But yeah I agree, CSS Variables support sounds like a good idea. I will investigate in it ;)

**Comment by JPeer264** [comment]
@klimashkin works in v`3.2.0` 💪

**Comment by klimashkin** [comment]
Awesome! Is it possible also to have a flag for that, similar to `replaceKeyframes`? Not always it's needed to be mangled : )

**Comment by JPeer264** [comment]
Ah whoops seems like that's the only option I forgot to put in the docs 😅 And it seems I have a kind of inconsistency in here, as my option is `ignoreCssVariables`, so by default it is set to `false`. I will rename `replaceKeyframes` in the next major release `ignoreKeyframes` and will also set it to `false` so I have some consitent options if that's ok for you ;)

**Comment by klimashkin** [comment]
Yes, that works, thanks!
