### ISSUE TITLE
CSS Custom Properties are not replaced in JS and html files

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rename-css-selectors#38]
He there! Seems like CSS Variables are mangled only in `.css` files, but if `.js` uses a variable then its original name is preserved, like here
```js
static defaultProps = {
  secondary: false,
  offset: 'var(--header-height)',
};
```
Also, variables in html file seem to be untouched. I declare a lot of them inline in the `:root` of `index.html` in `<style>` tag.

My config is:
```js
await rcs.process.auto(
  ['index.html', 'scripts/app?(.compat).js', 'styles/app?(.compat).css'], {
    cwd: config.release.dest,
    newPath: config.release.dest,
    overwrite: true,
    replaceKeyframes: true,
  }
);
```

**Comment by JPeer264** [comment]
Oh! Didn't thought of that case actually. I just handled those things in the css files. I'm on it!

**Comment by JPeer264** [comment]
@klimashkin sorry for the delay. Should work in v`3.2.2`
