### ISSUE TITLE
Option ignoreCssVariables doesn't get passed through

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rename-css-selectors#39]
Just now I've got to use `ignoreCssVariables` (https://github.com/JPeer264/node-rename-css-selectors/issues/37#issuecomment-491386867) option (sorry about the delay : ),
but it is not working, seems like it should be declared here: https://github.com/JPeer264/node-rename-css-selectors/blob/2561770c67c98b315a23eb93e5443c119379a41e/lib/process/process.js#L72 
I guess.

**Comment by JPeer264** [comment]
Fixed in v`3.2.2`
