### ISSUE TITLE
[BUG] It renames EJS

### ISSUE THREAD

**Issue by Chazza** [JPeer264/node-rename-css-selectors#64]
Hey there,

I've been obfuscating using this, however it's also renaming stuff inside of ejs tags, any way round this?

**Comment by JPeer264** [comment]
Hey, sorry for the late response. I assume this is the same issue as mentioned in https://github.com/JPeer264/node-rename-css-selectors/issues/20#issuecomment-648006247. Actually I do not handle EJS tags at all. Do you want to ignore them all the time?

**Comment by Chazza** [comment]
> #20 (comment)

Similar, can you let us configure extra regex filters, in my case `<%= x %>`

**Comment by JPeer264** [comment]
If that whole string gets replaced, yes, you can regex that whole thing with [setExclude](https://github.com/JPeer264/node-rcs-core/blob/master/docs/api/baselibrary.md#setexclude):

I think following would do the trick:
```js
const rcs = require('rcs-core');

rcs.baseLibrary.setExclude(/<%=[\s\S]+%>/);
```

**Comment by Chazza** [comment]
> If that whole string gets replaced, yes, you can regex that whole thing with [setExclude](https://github.com/JPeer264/node-rcs-core/blob/master/docs/api/baselibrary.md#setexclude):
> 
> I think following would do the trick:
> 
> ```js
> const rcs = require('rcs-core');
> 
> rcs.baseLibrary.setExclude(/<%=[\s\S]+%>/);
> ```

So I would use this before my obfuscation code?

**Comment by JPeer264** [comment]
Exactly 👍

**Comment by Chazza** [comment]
> Exactly 👍

Awesome, this works perfectly! Would be cool to documentate this perhaps.

**Comment by JPeer264** [comment]
Good point. I will add a snippet to the documentation
