### ISSUE TITLE
mismatched layout after running rcs

### ISSUE THREAD

**Issue by anuragphadke** [JPeer264/node-rename-css-selectors#67]
When I run the rcs, the output file has a layout that's is mismatched on the header side.

code:

const rcs = require('rename-css-selectors')
const args = process.argv;
const file = "_14.5.pre.html"
// callback
rcs.process.auto([file], (err) => {
    console.log(err);
    rcs.generateMapping('./', { overwrite: true }, (err) => {
        // the mapping file is now saved
    });
});

input: https://beta.webfast.co/_14.5.pre.html
output: https://beta.webfast.co/_14.6.pre.html
(mobile only)

Any idea why the header looks different post running rcs and what I can do to maintain consistent layout?

**Comment by anuragphadke** [comment]
Looks like if i add the `id` to the list of exclusions, then the layout gets fixed.
Closing the ticket.

**Comment by JPeer264** [comment]
Good that this could be fixed with a workaround. Still, can I ask you which version you run of `rename-css-selectors`?

**Comment by anuragphadke** [comment]
@JPeer264 : I am using the latest on npm..
`
"rename-css-selectors": "^3.3.0"
`
