### ISSUE TITLE
Keyframes support

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rename-css-selectors#7]
Now it doesn't touch `@keyframes` names, but would be great if it does

**Comment by JPeer264** [comment]
@klimashkin I moved it to https://github.com/JPeer264/node-rcs-core/issues/10

**Comment by JPeer264** [comment]
@klimashkin you can now reinstall `rename-css-selectors` (make sure your npm/yarn cache is empty) and you can now rename keyframes as following:

```js
rcs.processCssSync('**/*.css', { replaceKeyframes: true });
```
