### ISSUE TITLE
Exclude classes with special characters

### ISSUE THREAD

**Issue by claudia-romano** [JPeer264/node-rename-css-selectors#77]
Hi, I'm trying to exclude a class with a special character (e.g `.aspect-ratio-1:1`) adding it to my package.json file. 
In the CSS file, I use `.aspect-ratio-1\:1` to escape the special character, while in the package.json I do not need to escape it. Not sure if this is the reason, but it does not seem to be working. Should I use a different convention in the package.json file?

Thanks.

**Comment by JPeer264** [comment]
Hey @claudia-romano, thanks for your issue. If you want to exclude selectors you should not add `.` or `#`. So the correct selector to exclude your css class would be `aspect-ratio-1:1`. 

Which version do you use? So I can give a more detailed answer on how to use it.

**Comment by claudia-romano** [comment]
Hi, thanks for getting back. 

Yes I'm using `aspect-ratio1:1`:
https://www.dropbox.com/s/8s6pmkbopm0wgup/Screenshot%202021-06-23%20at%2008.37.42.png?dl=0

I'm using version 3.2. Thanks

**Comment by JPeer264** [comment]
Alright. It seems that there is a bug on `rcs-core` where it does remove the escaping. I will fix that asap and notify you as soon as it will be fixed.

**Comment by claudia-romano** [comment]
Thanks!

**Comment by JPeer264** [comment]
Sorry for getting back so late. But this should be fixed in v`4.0.0`. And `rcs-core@3.6.4`. The only thing which should have been changed is following:

`rcs.includeConfig()` -> `rcs.config.load()`
`rcs.loadMapping()` -> `rcs.mapping.load()`
`rcs.generateMapping()` -> `rcs.mapping.generate()`

All the rest should have remained the same.

**Comment by claudia-romano** [comment]
It's working now. Thanks for your help!
