### ISSUE TITLE
Does this plugin optimize the library so most frequent classes get one letter not two?

### ISSUE THREAD

**Issue by universemaster** [JPeer264/node-rename-css-selectors#80]
Step 2 from the instructions for  [rcs-core](https://github.com/JPeer264/node-rcs-core) are to run `rcs.optimize()`.

Please excuse my ignorance, but does this plugin `node-rename-css-selectors` actually optimize the library so that the most used classes get one letter, not two?

**Comment by JPeer264** [comment]
Hey @universemaster

Actually you are right, I totally forgot to add the optimization in this library. Thanks for pointing this out

**Comment by JPeer264** [comment]
Available in v`4.1.0`. It is enabled by default and can be disabled by passing the option: `optimize: false`
