### ISSUE TITLE
Minify as a function

### ISSUE THREAD

**Issue by viktordre2** [JPeer264/node-rename-css-selectors#82]
Hello, I'm sorry for maybe stupid question, but is there an official way I could minify some html page with inline (using tags) styles and scripts.
The problem is I have variable with some html content, and need to get result as a variable. I'm not able to create files)

**Comment by JPeer264** [comment]
Hey. If I understand you correctly you have the HTML code already as a variable? If so you could use `rcs-core` directly (as `rename-css-selectors` is just a wrapper around `rcs-core`) and check the [usage section](https://github.com/JPeer264/node-rcs-core#usage)

```js
import rcs from 'rcs-core';

const renamedHTML = rcs.replace.html(myHTML);
```

Is this what you want to achieve?

**Comment by JPeer264** [comment]
Please reopen if this is still an issue.
