### ISSUE TITLE
Unchanging custom class name

### ISSUE THREAD

**Issue by mertgibi** [JPeer264/node-rename-css-selectors#92]
console
```
WARNING: The following selectors got found but were ignored. please check if you do not want to allow these selectors instead
 - 'center' found in:
    ./pages/category.html(1):
Successfully wrote new files
```

category.html first 3 line
```
<section class="ov center">
    <div class="dr na iw sc lo r">
        <div class="om lt">
```

I want it to change in center but I don't understand how to do it

**Comment by JPeer264** [comment]
Hey `center` is not included by default as it is part of the defualt HTML ([see more here](https://github.com/JPeer264/node-rcs-core/blob/main/docs/caveats.md#caveats-for-step-2) and the [default excluded list](https://github.com/JPeer264/node-rcs-core/blob/main/lib/helpers/excludeList.ts#L152)).

To activate it you can use `.setInclude` as written in the *Usage* section in the README: https://github.com/JPeer264/node-rcs-core#usage. Please reopen the issue if it still happen
